import type { CertificationEntry } from "./types";

export const certifications: CertificationEntry[] = [
  {
    id: "cert-orleans",
    title: "Microsoft Orleans .NET",
    issuer: "Udemy",
    dateLabel: "Jan 2025",
    verificationUrl: "https://www.udemy.com/certificate/UC-b78fee6a-48a0-48a5-ab96-75937b574536/",
  },
  {
    id: "cert-zscaler-ztca",
    title: "Zero Trust Certified Associate (ZTCA)",
    issuer: "Zscaler",
    dateLabel: "Jan 2024 · Expires Jan 2027",
    credentialId: "9xxdrwm3j4gv",
    verificationUrl: "https://verify.skilljar.com/c/9xxdrwm3j4gv",
  },
  {
    id: "cert-wipro-talentnext",
    title: "TalentNext JAVA Full Stack",
    issuer: "Wipro",
    dateLabel: "Sep 2023",
    verificationUrl: "https://cert.diceid.com/csr/cid/YaNeGp",
  },
  {
    id: "cert-zscaler-fundamentals",
    title: "Zscaler Cybersecurity Fundamentals Associate Exam",
    issuer: "Zscaler",
    dateLabel: "Sep 2023 · Expires Sep 2026",
    credentialId: "e52p8ufsp83q",
    verificationUrl: "https://verify.skilljar.com/c/e52p8ufsp83q",
  },
  {
    id: "cert-google-data-analytics",
    title: "Google Data Analytics Certificate",
    issuer: "Google",
    dateLabel: "Aug 2023",
    credentialId: "QHYVR53L2UTP",
    verificationUrl: "https://www.coursera.org/account/accomplishments/specialization/certificate/QHYVR53L2UTP",
  },
  {
    id: "cert-unstop-ecommerce-11",
    title: "Certificate of Participation in Level 1.1: E-Commerce",
    issuer: "Unstop",
    dateLabel: "Aug 2023",
    credentialId: "23befc43-2643-4cfd-bfc3-1eb3ce8d1795",
    verificationUrl: "https://unstop.com/certificate-preview/23befc43-2643-4cfd-bfc3-1eb3ce8d1795",
  },
  {
    id: "cert-coding-ninjas-pointers",
    title: "Pointers",
    issuer: "Coding Ninjas",
    dateLabel: "",
    verificationUrl: "https://files.codingninjas.in/certi_image278661a2f5a1611585411d6f5d15075573b3c7.jpg",
  },
  {
    id: "cert-google-cloud-engineer",
    title: "Google Cloud Engineer Path",
    issuer: "Google Cloud",
    dateLabel: "Jan 2023",
    verificationUrl: "https://www.cloudskillsboost.google/public_profiles/e6fd3698-c0e3-4e0d-825b-3ccccd40465c",
  },
  {
    id: "cert-coursera-ml",
    title: "Machine Learning",
    issuer: "Coursera",
    dateLabel: "Jul 2023",
    credentialId: "TS98C9KSJJRC",
    verificationUrl: "https://www.coursera.org/account/accomplishments/specialization/certificate/TS98C9KSJJRC",
  },
  {
    id: "cert-coursera-unsupervised",
    title: "Unsupervised Learning, Recommenders, Reinforcement Learning",
    issuer: "Coursera",
    dateLabel: "Jul 2023",
    verificationUrl: "https://www.coursera.org/account/accomplishments/certificate/DBB3XZK8KVBX",
  },
  {
    id: "cert-cisco-ccna",
    title: "CCNA: Introduction to Networks",
    issuer: "Cisco",
    dateLabel: "Jul 2023",
  },
  {
    id: "cert-cisco-cybersecurity-essentials",
    title: "Cybersecurity Essentials",
    issuer: "Cisco",
    dateLabel: "Mar 2023",
  },
  {
    id: "cert-cisco-intro-cybersecurity",
    title: "Introduction to Cybersecurity",
    issuer: "Cisco",
    dateLabel: "Jun 2023",
  },
  {
    id: "cert-lnt-crnn",
    title: "Cursive Handwritten Data Recognition using CRNN",
    issuer: "L&T Technology Services",
    dateLabel: "Dec 2022",
  },
  {
    id: "cert-azure-data-scientist",
    title: "Microsoft Certified: Azure Data Scientist Associate",
    issuer: "Microsoft",
    dateLabel: "Jan 2023 · Expired Jan 2024",
  },
  {
    id: "cert-nptel-dsa-java",
    title: "Data Structures and Algorithms using Java",
    issuer: "NPTEL",
    dateLabel: "Nov 2022",
  },
  {
    id: "cert-hack-the-mountains",
    title: "Hack The Mountains 3.O",
    issuer: "Hack The Mountains",
    dateLabel: "Aug 2022",
    credentialId: "4d27de0a-3ee5-417c-8497-c8bb1ce7621b",
  },
  {
    id: "cert-hackerrank-problem-solving",
    title: "Problem Solving (Basic)",
    issuer: "HackerRank",
    dateLabel: "Sep 2022",
  },
  {
    id: "cert-coursera-azure-ml-pipelines",
    title: "Machine Learning Pipelines with Azure ML Studio",
    issuer: "Coursera",
    dateLabel: "Sep 2022",
    credentialId: "TAY9ERV7NE6A",
  },
  {
    id: "cert-aws-ml-foundations",
    title: "AWS Academy Graduate — AWS Academy Machine Learning Foundations",
    issuer: "AWS",
    dateLabel: "Sep 2022",
  },
  {
    id: "cert-aws-cloud-foundations",
    title: "AWS Academy Graduate — AWS Academy Cloud Foundations",
    issuer: "AWS",
    dateLabel: "Sep 2022",
  },
  {
    id: "cert-coursera-advanced-learning-algorithms",
    title: "Advanced Learning Algorithms",
    issuer: "Coursera",
    dateLabel: "Sep 2022",
    credentialId: "5998V842M5UQ",
  },
  {
    id: "cert-coursera-supervised-ml",
    title: "Supervised Machine Learning: Regression and Classification",
    issuer: "Coursera",
    dateLabel: "Aug 2022",
    credentialId: "6QPXT224DADQ",
  },
  {
    id: "cert-unstop-ecommerce-1",
    title: "Certificate of Participation in Level 1: E-Commerce",
    issuer: "Unstop",
    dateLabel: "Jul 2022",
    credentialId: "3d590f80-918a-44ba-9507-b7afed12bdb5",
  },
];
